### ISSUE TITLE
Spelling for Classifier

### ISSUE THREAD

**Issue by azibit** [IML-DKFZ/realistic-al#1]
https://github.com/IML-DKFZ/realistic-al/blob/1a653ae1eff73467fafaba0e88481684675e3d7d/src/query/query_diversity.py#L161

The spelling for classifier is causing some errors on the above line, classifier in the code is missing an i.

**Comment by sten2lu** [comment]
Hi @azibit,
thank you for letting me know.
I just fixed it.
